import type { Metadata } from "next";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Header from "./header/header";
import logout from "./auth/logout";
import authenticated from "./auth/actions/authenticated";
import Providers from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated()
  
  return (
    <html lang="en">
      <body>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />
          <Container className={isAuthenticated ? "mt-10" : ""}>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
